### PR TITLE
Fix load dependencies (bug #2)

### PR DESCRIPTION
**Pull request by kirillkomlev**
Fix to use codacycoverage like global utility

### CODE REVIEW

**Comment by haffla** [comment]
Hello kirillkomlev,

thanks for your input. You are right. It does not work if you install php-codacy-coverage globally. The changes you submit though, would only work for people who install it globally. 

It would be nice if you could make both globally and locally installations work. Something like:

```php
if(file_exists(.......)) { ........ }
else if file_exists(.......)) { ........ }
else { some error output?! }
```

Thank you.

**Comment by kirillkomlev** [comment]
Hello, haffla. 

Have you tested this solution? I have. It's work both globally and locally.

Let's explain.  `__DIR__` absolute path where file really located. If file is symbolic link, `__DIR__` has a path to really file. It doesn't matter where  you exec codacycoverage, __DIR__ return path where bin/codacycoverage really located.  

Add in the beginning of codacycoverage
```php
#!/usr/bin/env php
<?php

die('__DIR__ = ' . __DIR__);
```
Result output:
```bash
cd ~/projects/project1
pwd 
Out: /home/komnac/projects/project1

codacycoverage
/home/komnac/.composer/vendor/bin/codacycoverage  
Out: __DIR__ = /home/komnac/.composer/vendor/codacy/coverage/bin

vendor/bin/codacycoverage
/home/komnac/projects/project1/vendor/bin/codacycoverage 
Out: __DIR__ =  /home/komnac/projects/project1/vendor/codacy/coverage/bin
```

There for `__DIR__ . '/../../../` is absolutely path to `vendor` dir *where codacycoverage installed*. And it's work always, until you reallocated `codacycoverage` in another place. I test this solution on Linux and Windows.

**Comment by kirillkomlev** [comment]
I found situation, where `__DIR__ . '/../../../autoload.php'` does not work. 
If I clone your project, and want to run bin/codacycoverage directly this cause a problem. So I fix it.
Now, if you found any situation you may simplify add file as element of array `$files`

**Comment by haffla** [comment]
I like your solution and I have tested it on Linux. I wonder if ```php /../.. ``` will work on Windows?! Have you tested this?

**Comment by kirillkomlev** [comment]
Yes, it's work on Windows (tested on 7 and 8) too.

This is interesting feature PHP, that allow you use `/` like a path separator and in most cases it's work correctly both on Linux and Windows (except eval or exec).

**Comment by rtfpessoa** [comment]
looks good to me. @haffla, ready for merge?

**Comment by kirillkomlev** [comment]
Yes.

**Comment by kirillkomlev** [comment]
Already implemented in #10.

**Pull request closed without merging**
